- id: '1579025080428'
  alias: Dim the lights
  description: ''
  trigger:
  - entity_id: media_player.living_room_atv
    from: paused
    platform: state
    to: playing
  condition:
  - after: sunset
    condition: sun
  - condition: state
    entity_id: light.living_room
    state: 'on'
  action:
  - alias: ''
    data:
      brightness: 136
      entity_id: light.living_room
      rgb_color:
      - 255
      - 216
      - 133
      transition: 4
    entity_id: light.living_room
    service: light.turn_on
- id: '1579025634569'
  alias: Brighten lights
  description: ''
  trigger:
  - entity_id: media_player.living_room
    from: playing
    platform: state
    to: paused
  condition:
  - after: sunset
    condition: sun
  - condition: state
    entity_id: light.living_room
    state: 'on'
  action:
  - data:
      brightness_pct: 100
      rgb_color:
      - 255
      - 216
      - 133
      transition: 4
    entity_id: light.living_room
    service: light.turn_on
- id: '1579110396845'
  alias: Dim the lights from idle
  description: ''
  trigger:
  - entity_id: media_player.living_room
    from: idle
    platform: state
    to: playing
  condition:
  - after: sunset
    condition: sun
  - condition: state
    entity_id: light.living_room
    state: 'on'
  action:
  - data:
      brightness_pct: 50
      entity_id: light.living_room
      rgb_color:
      - 255
      - 216
      - 133
      transition: 4
    entity_id: light.living_room
    service: light.turn_on
- id: '1591477324212'
  alias: Rubbish bin notification
  description: Sends a notification to alexa for rubbish bins to be collected tomorrow
  trigger:
  - at: '19:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: sensor.rubbish_date
    state: tomorrow
  action:
  - data:
      data:
        type: tts
      message: Rubbish is collected tomorrow
    service: notify.alexa_media_living_room_dot
- id: '1591477396917'
  alias: Recycling bin notification
  description: ''
  trigger:
  - at: '19:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: sensor.recycling_date
    state: tomorrow
  action:
  - data:
      data:
        type: tts
      message: Recycling is collected tomorrow
    service: notify.alexa_media_living_room_dot
- id: '1591477662742'
  alias: Garden bin notification
  description: ''
  trigger:
  - at: '19:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: sensor.garden_date
    state: tomorrow
  action:
  - data:
      data:
        type: tts
      message: Garden waste is collected tomorrow
    service: notify.alexa_media_living_room_dot
