- id: '1579025080428'
  alias: Dim the lights
  description: ''
  trigger:
  - entity_id: media_player.living_room_atv
    from: paused
    platform: state
    to: playing
  condition:
  - after: sunset
    condition: sun
  - condition: state
    entity_id: light.living_room
    state: 'on'
  action:
  - alias: ''
    data:
      brightness: 136
      entity_id: light.living_room
      rgb_color:
      - 255
      - 216
      - 133
      transition: 4
    entity_id: light.living_room
    service: light.turn_on
- id: '1579025634569'
  alias: Brighten lights
  description: ''
  trigger:
  - entity_id: media_player.living_room
    from: playing
    platform: state
    to: paused
  condition:
  - after: sunset
    condition: sun
  - condition: state
    entity_id: light.living_room
    state: 'on'
  action:
  - data:
      brightness_pct: 100
      rgb_color:
      - 255
      - 216
      - 133
      transition: 4
    entity_id: light.living_room
    service: light.turn_on
- id: '1579110396845'
  alias: Dim the lights from idle
  description: ''
  trigger:
  - entity_id: media_player.living_room
    from: idle
    platform: state
    to: playing
  condition:
  - after: sunset
    condition: sun
  - condition: state
    entity_id: light.living_room
    state: 'on'
  action:
  - data:
      brightness_pct: 50
      entity_id: light.living_room
      rgb_color:
      - 255
      - 216
      - 133
      transition: 4
    entity_id: light.living_room
    service: light.turn_on
