- id: '1579025080428'
  alias: Dim the lights
  description: ''
  trigger:
  - entity_id: media_player.living_room_atv
    from: paused
    platform: state
    to: playing
  condition:
  - after: sunset
    condition: sun
  - condition: state
    entity_id: light.living_room
    state: 'on'
  action:
  - alias: ''
    data:
      brightness: 136
      entity_id: light.living_room
      rgb_color:
      - 255
      - 216
      - 133
      transition: 4
    entity_id: light.living_room
    service: light.turn_on
- id: '1579025634569'
  alias: Brighten lights
  description: ''
  trigger:
  - entity_id: media_player.living_room
    from: playing
    platform: state
    to: paused
  condition:
  - after: sunset
    condition: sun
  - condition: state
    entity_id: light.living_room
    state: 'on'
  action:
  - data:
      brightness_pct: 100
      rgb_color:
      - 255
      - 216
      - 133
      transition: 4
    entity_id: light.living_room
    service: light.turn_on
- id: '1579110396845'
  alias: Dim the lights from idle
  description: ''
  trigger:
  - entity_id: media_player.living_room
    from: idle
    platform: state
    to: playing
  condition:
  - after: sunset
    condition: sun
  - condition: state
    entity_id: light.living_room
    state: 'on'
  action:
  - data:
      brightness_pct: 50
      entity_id: light.living_room
      rgb_color:
      - 255
      - 216
      - 133
      transition: 4
    entity_id: light.living_room
    service: light.turn_on
- id: '1591477324212'
  alias: Rubbish bin notification
  description: Sends a notification to alexa for rubbish bins to be collected tomorrow
  trigger:
  - at: '18:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: sensor.rubbish_date
    state: tomorrow
  action:
  - data:
      data:
        type: tts
      message: Rubbish bin is collected tomorrow
    service: notify.alexa_media_living_room_dot
  mode: single
- id: '1591477396917'
  alias: Recycling bin notification
  description: ''
  trigger:
  - at: '18:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: sensor.recycling_date
    state: tomorrow
  action:
  - data:
      data:
        type: tts
      message: Recycling is collected tomorrow
    service: notify.alexa_media_living_room_dot
  mode: single
- id: '1591477662742'
  alias: Garden bin notification
  description: ''
  trigger:
  - at: '18:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: sensor.garden_date
    state: tomorrow
  action:
  - data:
      data:
        type: tts
      message: Garden waste is collected tomorrow
    service: notify.alexa_media_living_room_dot
  mode: single
- id: '1599769260667'
  alias: Bedroom Fan Night Mode
  description: ''
  trigger:
  - at: '21:30:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: fan.bedroom
      night_mode: true
    service: dyson.set_night_mode
  - data:
      auto_mode: true
      entity_id: fan.bedroom
    service: dyson.set_auto_mode
  mode: single
- id: '1600004952451'
  alias: Bedroom Fan Auto Mode
  description: ''
  trigger:
  - at: 09:30:00
    platform: time
  condition: []
  action:
  - data:
      auto_mode: true
      entity_id: fan.bedroom
    service: dyson.set_auto_mode
  - data:
      entity_id: fan.bedroom
      night_mode: false
    service: dyson.set_night_mode
  mode: single
- id: '1603014824114'
  alias: Front Door Open
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.front_door_sensor
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.alexa_media_bedroom_dot
    data:
      data:
        type: tts
      message: Front door open
  - service: notify.alexa_media_kitchen_dot
    data:
      data:
        type: tts
      message: Front door open
  - service: notify.alexa_media_computer_room_dot
    data:
      data:
        type: tts
      message: Front door open
  mode: single
- id: '1603015015437'
  alias: Back Door Open
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.back_door_sensor
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.alexa_media_kitchen_dot
    data:
      data:
        type: tts
      message: Back door open
  - service: notify.alexa_media_bedroom_dot
    data:
      data:
        type: tts
      message: Back door open
  - service: notify.alexa_media_computer_room_dot
    data:
      data:
        type: tts
      message: Back door open
  mode: single
