homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 108
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml
  external_url: !secret external_url
  internal_url: !secret internal_url
  media_dirs:
    logos: /media/logos

# Load all default components
default_config:

# Load themes directory
frontend:
  themes: !include_dir_merge_named themes

# Automatic device discovery
discovery:
  enable:

# Enable BWAlarm integration
alarm_control_panel: !include resources/bwalarm/bwalarm.yaml

# Monitor Docker containers
monitor_docker:
  - name: Docker
    monitored_conditions:
      - allinone

# Dyson Air Purifier
dyson:
  username: !secret email
  password: !secret dyson_p
  language: GB
  devices:
    - device_id: !secret dyson_s
      device_ip: 192.168.1.130

# Enable Home Assistant API
api:

# Alexa
alexa:
  smart_home:
    locale: en-GB
    endpoint: https://api.eu.amazonalexa.com/v3/events
    client_id: !secret alexa_clientid
    client_secret: !secret alexa_clientsecret
    filter:
      include_domains:
        - script
        - fan
      exclude_domains:
        - light
        - camera
        - automation
        - media_player
        - binary_sensor

# Sabnzbd
sabnzbd:
  api_key: !secret sab_api
  host: !secret sab_host
  name: sab
  port: 443
  ssl: true
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - queue_count
    - day_size
    - week_size
    - month_size
    - total_size

# Wake on LAN
wake_on_lan:

# HTML5 notifications
notify:
  - platform: html5
    name: browser
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret email

# Zones
zone:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  radius: 50
  icon: mdi:home

# Debug logs
#logger:
#  default: critical
#  logs:
#    pyatv: debug
#    custom_components.apple_tv: debug

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
