# Media
- platform: rest
  name: SkyQ living room
  resource: http://192.168.1.163:9006/as/system/information
  json_attributes:
    - systemUptime
    - activeStandby
  device_class: power
  value_template: "{% if (value_json.activeStandby == False) %}on{% else %}off{% endif %}"

#- platform: metoffice
#  api_key: !secret metofficeapi
#  monitored_conditions:
#    - weather
#    - temperature
#    - feels_like_temperature
#    - wind_speed
#    - wind_direction
#    - wind_gust
#    - visibility
#    - visibility_distance
#    - uv
#    - precipitation
#    - humidity

# Rubbish collection
- platform: command_line
  name: Rubbish collection
  scan_interval: 3600
  command: '/config/scripts/rubbish.sh'

# Recycling collection
- platform: command_line
  name: Recycling collection
  scan_interval: 3600
  command: '/config/scripts/recycling.sh'

# Garden waste collection
- platform: command_line
  name: Garden waste collection
  scan_interval: 3600
  command: '/config/scripts/garden.sh'

# Rubbish date extract
- platform: command_line
  name: Rubbish date
  scan_interval: 3600
  command: '/config/scripts/rubbish_date.sh'

# Recycling date extract
- platform: command_line
  name: Recycling date
  scan_interval: 3600
  command: '/config/scripts/recycling_date.sh'

# Garden waste date extract
- platform: command_line
  name: Garden date
  scan_interval: 3600
  command: '/config/scripts/garden_date.sh'

